### ISSUE TITLE
Build failing - has FARA website changed?

### ISSUE THREAD

**Issue by ssempervirens** [simonw/fara-history#4]
I work on data analysis and apps at the AP and a reporter mentioned that they thought that this tool wasn't updating correctly. I took a look and noticed that the build is currently failing, and when I try to run `build_database.py` I get an error that the Registration Number is not numeric. Upon examination, the Registration Number in the data is "SPAIN" and "SUDAN" depending on the input and it looks like many of the key value pairs are not mapped correctly in the data dictionary. I'm wondering if it's that the FARA website changed recently, and so this scraper is up to date? 

I am sure you all have lots going on, but just curious whether this is something you all are planning to update and maintain or whether you'd be seeking help in resolving this issue. Thanks!

**Comment by simonw** [comment]
Here's an error from a recent run: https://github.com/simonw/fara-history/runs/2694237245?check_suite_focus=true
```
[master 63f9dce] 2 rows added
 1 file changed, 2 insertions(+)
Traceback (most recent call last):
  File "sort_csv.py", line 21, in <module>
    sort_csv(filepath)
  File "sort_csv.py", line 12, in sort_csv
    rows = [r for r in reader]
  File "sort_csv.py", line 12, in <listcomp>
    rows = [r for r in reader]
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4305: invalid continuation byte
```

**Comment by simonw** [comment]
Looks like the file may be encoded in `latin-1` but treated as `utf-8`.

**Comment by simonw** [comment]
That fixed it! https://github.com/simonw/fara-history/actions/runs/886303161 ran cleanly and deployed the latest data to the https://fara.datasettes.com/ site.
